### ISSUE TITLE
84 step solution to 20-Multiplication Workshop

### ISSUE THREAD

**Issue by peterfreese** [atesgoral/human-resource-machine-solutions#24]
I have an 84 step solution to 20-Multiplication Workshop. I'd like to submit it, but when I try to create a PR using GitHub desktop, I get:

Sync failed to push local changes
It seems you do not have permission to push your changes to this repository.

I'm new to github, and I'm probably doing something incorrectly. I've cloned the repo, created a branch, and commited my local changes to the branch. Should I be able to create a PR at this step?

**Comment by atesgoral** [comment]
This might help: https://yangsu.github.io/pull-request-tutorial/

I think the issues you're having is due to the fact that you've directly made a local clone of this repository (typically called the "origin" in this case). And you naturally don't have permission to directly push to this repository (unless you're explicitly granted co-ownership). You should instead first create a fork on GitHub, to have your own copy of the repo, and then create a branch in your own repo. Then, you can create a PR against the origin repo.

**Comment by peterfreese** [comment]
Thanks - that was exactly what I did wrong. The PR from my fork should now be submitted.

**Comment by atesgoral** [comment]
I'm glad that helped. Thanks for that great speed boost :)
